apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.name
  targets:
  - select:
      kind: Terraform
    fieldPaths:
    - metadata.name
    - spec.varsFrom.[kind=ConfigMap].name
    - spec.writeOutputsToSecret.name
    options:
      delimiter: '-'
      index: 0    