apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: example-cluster
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  storeReadablePlan: human
  path: ./workload-eks-tf-module-github
  runnerPodTemplate:
    spec:
      image: ghcr.io/infinitydon/fluxcd-tf-controller-awscli:v0.16.0-rc.4  
  sourceRef:
    kind: GitRepository
    name: eks-infra-tf-repo
    namespace: flux-system
  vars:
  - name: region
    value: AWS_REGION
  - name: eks_cluster_name
    value: EKS_CLUSTER_NAME
  - name: eks_cluster_version
    value: EKS_VERSION
  - name: node_instance_type
    value: INSTANCE_TYPE
  - name: parameter_store_name
    value: PARAMETER_STORE_NAME
  - name: create_external_dns
    value: CREATE_EXTERNAL_DNS
  - name: external_dns_domain_name
    value: EXT_DNS_NAME
  - name: use_ubuntu_ami
    value: USE_UBUNTU_AMI
  writeOutputsToSecret:
    name: example-outputs   