apiVersion: req.nephio.org/v1alpha1
kind: Capacity
metadata:
  name: control-plane
  namespace: oai-core
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.smf-core
    specializer.nephio.org/namespace: oai-core
spec:
  maxSessions: 500
  maxNFConnections: 5
