apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: udr-example
  namespace: udr-example
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true  
spec:
  provider: udr.openairinterface.org