apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: cucp-ran-amf-core
  namespace: oai-ran-cucp
  annotations:
    specializer.nephio.org/owner: req.nephio.org/v1alpha1.Dependency.amf
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: amf-core
      namespace: oai-ran-cucp
    spec:
      provider: amf.openairinterface.org
      capacity:
        maxSubscribers: 1000
      interfaces:
      - name: n2
        ipv4:
          address: AMF_N2_IP # kpt-set: ${amf-n2-ip-address}
          gateway: AMF_N2_GW # kpt-set: ${amf-n2-ip-gateway}
        vlanID: 30
      networkInstances:
      - name: vpc-ran
        interfaces:
        - n2
      parametersRefs:
      - name: oai-amf-config
        apiVersion: workload.nephio.org/v1alpha1
        kind: NFConfig