apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: amf-core-n2-test
  namespace: oai-core
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "amf-core-n2",
      "plugins": [
        {
          "type": "CNI_PLUGIN",
          "capabilities": {
            "ips": true
          },
          "master": "AMF_N2_MULTUSPARENTINTERFACE",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "CUCP_N2_NETWORKADDRESS", "gw": "AMF_N2_GW" }]
          }
        }
      ]
    }