apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: du-edge-f1
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "du-edge-f1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "DU_F1U_MULTUSPARENTINTERFACE",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }            