apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-oai-amf
spec:
  upstream:
    repo: nephio-aws-packages
    package: oai-amf-package
    revision: main
  downstream:
    repo: control-plane
    package: oai-amf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core