apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-oai-ausf
spec:
  upstream:
    repo: nephio-aws-packages
    package: oai-ausf-package
    revision: main
  downstream:
    repo: control-plane
    package: oai-ausf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core
