apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: cnf-ip-mgmt-api
spec:
  upstream:
    repo: nephio-aws-packages
    package: configuration-ip-api-package
    revision: main
  downstream:
    repo: mgmt
    package: configuration-ip-api
  annotations:
    approval.nephio.org/policy: initial
