apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-oai-database
spec:
  upstream:
    repo: nephio-aws-packages
    package: database-package
    revision: r3
  downstream:
    repo: control-plane
    package: database
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core
