apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: day0-infra
spec:
  upstream:
    repo: nephio-aws-packages
    package: infra-day0-package
    revision: r3-argocd
  downstream:
    repo: mgmt
    package: infra-day0-package
  annotations:
    approval.nephio.org/policy: initial    
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configMap:
        github-org: infinitydon
        deployment-region: us-west-2
        workload-ran-az1: us-west-2a
        workload-ran-az2: us-west-2b
        workload-core-controlplane-az1: us-west-2a
        workload-core-controlplane-az2: us-west-2b
        workload-core-userplane-az1: us-west-2a
        workload-core-userplane-az2: us-west-2b
        multus-lambda-s3-bucket: multus-lambda-us-west-2-oregon-2024-argo
        github-pat-secret-name: github-pat-credentials
        github-repos: '["argo-telco-ran-5g", "argo-telco-control-plane-5g", "argo-telco-user-plane-5g"]'
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: Terraform
      configMap:
        by-value: IRSA_ARN
        put-value: arn:aws:iam::ACCOUNT_ID:role/mgmt-argocd-terraform-runner