apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: kyverno-amf-awsipmgt-injection
spec:
  upstream:
    repo: nephio-aws-packages
    package: kyverno-awsipmgt-core-package
    revision: r3
  downstream:
    repo: control-plane
    package: kyverno-amf-injection
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: CLUSTER_POLICY_NAME
        put-value: amf-multus-awsipmgt-injection
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: POD_LABEL_VALUE
        put-value: "amf"
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: kyverno-smf-awsipmgt-injection
spec:
  upstream:
    repo: nephio-aws-packages
    package: kyverno-awsipmgt-core-package
    revision: r3
  downstream:
    repo: control-plane
    package: kyverno-smf-injection
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: CLUSTER_POLICY_NAME
        put-value: smf-multus-awsipmgt-injection
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: POD_LABEL_VALUE
        put-value: "smf"
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: kyverno-upf-awsipmgt-injection
spec:
  upstream:
    repo: nephio-aws-packages
    package: kyverno-awsipmgt-core-package
    revision: r3
  downstream:
    repo: user-plane
    package: kyverno-upf-injection
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: CLUSTER_POLICY_NAME
        put-value: upf-multus-awsipmgt-injection
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: POD_LABEL_VALUE
        put-value: "upf"
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: kyverno-cucp-awsipmgt-injection
spec:
  upstream:
    repo: nephio-aws-packages
    package: kyverno-awsipmgt-ran-package
    revision: r3
  downstream:
    repo: ran
    package: kyverno-cucp-injection
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: CLUSTER_POLICY_NAME
        put-value: cucp-multus-awsipmgt-injection
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: POD_LABEL_VALUE
        put-value: "oai-gnb-cu-cp"        
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: kyverno-cuup-awsipmgt-injection
spec:
  upstream:
    repo: nephio-aws-packages
    package: kyverno-awsipmgt-ran-package
    revision: r3
  downstream:
    repo: ran
    package: kyverno-cuup-injection
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: CLUSTER_POLICY_NAME
        put-value: cuup-multus-awsipmgt-injection
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: POD_LABEL_VALUE
        put-value: "oai-gnb-cu-up"
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: kyverno-du-awsipmgt-injection
spec:
  upstream:
    repo: nephio-aws-packages
    package: kyverno-awsipmgt-ran-package
    revision: r3
  downstream:
    repo: ran
    package: kyverno-du-injection
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: CLUSTER_POLICY_NAME
        put-value: du-multus-awsipmgt-injection
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: ClusterPolicy
      configMap:
        by-value: POD_LABEL_VALUE
        put-value: "oai-gnb-du"