apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-upf
spec:
  upstream:
    repo: nephio-aws-packages
    package: oai-upf-edge-package
    revision: r3
  downstream:
    repo: user-plane
    package: oai-upf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge
