apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: ran-eks-cluster
spec:
  upstream:
    repo: nephio-aws-packages
    package: workload-cluster-package
    revision: r3-argocd
  downstream:
    repo: mgmt
    package: ran
  annotations:
    approval.nephio.org/policy: initial     
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: Terraform
      configMap:
        by-value: IRSA_ARN
        put-value: arn:aws:iam::ACCOUNT_ID:role/mgmt-argocd-terraform-runner
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: Terraform
      configMap:
        by-value: FUNCTION
        put-value: ran
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configMap:
        aws-region: us-west-2
        eks-cluster-name: ran
        eks-version: "\"1.29\""
        instance-type: m5.4xlarge
        parameter-store-name: ran-5g
        tf-backend-config: |-
           terraform {
             backend "kubernetes" {
               secret_suffix    = "ran-cluster"
               in_cluster_config  = true
               namespace = "tf-system"
             }
           }
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: controlplane-eks-cluster
spec:
  upstream:
    repo: nephio-aws-packages
    package: workload-cluster-package
    revision: r3-argocd
  downstream:
    repo: mgmt
    package: controlplane
  annotations:
    approval.nephio.org/policy: initial     
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: Terraform
      configMap:
        by-value: IRSA_ARN
        put-value: arn:aws:iam::ACCOUNT_ID:role/mgmt-argocd-terraform-runner
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: Terraform
      configMap:
        by-value: FUNCTION
        put-value: controlplane
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configMap:
        aws-region: us-west-2
        eks-cluster-name: ctrlplane
        eks-version: "\"1.29\""
        instance-type: m5.4xlarge
        parameter-store-name: control-plane-5g
        tf-backend-config: |-
           terraform {
             backend "kubernetes" {
               secret_suffix    = "ctrlplane-cluster"
               in_cluster_config  = true
               namespace = "tf-system"
             }
           }
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: userplane-eks-cluster
spec:
  upstream:
    repo: nephio-aws-packages
    package: workload-cluster-package
    revision: r3-argocd
  downstream:
    repo: mgmt
    package: userplane
  annotations:
    approval.nephio.org/policy: initial     
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: Terraform
      configMap:
        by-value: IRSA_ARN
        put-value: arn:aws:iam::ACCOUNT_ID:role/mgmt-argocd-terraform-runner
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: Terraform
      configMap:
        by-value: FUNCTION
        put-value: userplane
    - image: gcr.io/kpt-fn/apply-setters:v0.2.0
      configMap:
        aws-region: us-west-2
        eks-cluster-name: userplane
        eks-version: "\"1.29\""
        instance-type: m5.4xlarge
        parameter-store-name: user-plane-5g
        tf-backend-config: |-
           terraform {
             backend "kubernetes" {
               secret_suffix    = "userplane-cluster"
               in_cluster_config  = true
               namespace = "tf-system"
             }
           }