apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-n2
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-n2",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "ens8",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "10.1.3.0/24", "gw": "10.0.5.1" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-f1c
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-f1c",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "ens6",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-e1
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-e1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "ens7",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }