apiVersion: v1
kind: Namespace
metadata:
  name: example
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true  
  labels:
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/enforce: "privileged"
