apiVersion: v1
kind: Namespace
metadata:
  name: oai-ran-cucp
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false  
  labels:
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    pod-security.kubernetes.io/enforce: "privileged"
