apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: day0-infra
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'infra.contrib.fluxcd.io|Terraform|flux-system|example-cluster'
spec:
  interval: 1m
  approvePlan: auto
  path: ./tgw-vpc-subnet-nat-terraform
  sourceRef:
    kind: GitRepository
    name: eks-infra-tf-repo
    namespace: flux-system
  vars:
  - name: github_org
    value: GITHUB_ORG
  - name: workload_cluster_region
    value: WORKLOAD_CLUSTER_REGION
  - name: attach_2nd_eni_lambda_s3_bucket
    value: MULTUS_LAMBDA_S3_BUCKET
  varsFrom:
  - kind: Secret
    name: github-pat-credentials
  writeOutputsToSecret:
    name: day0-infra-outputs