apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: nrf-example
  namespace: nrf-example
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
spec:
  provider: nrf.openairinterface.org
