apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: nrf-example
  namespace: nrf-example
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider: nrf.openairinterface.org
