apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-edge-n3
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cuup-edge-n3",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "CUUP_N3_MULTUSPARENTINTERFACE",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "UPF_N3_NETWORKADDRESS", "gw": "CUUP_N3_GW" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-edge-f1u
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cuup-edge-f1u",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "CUUP_F1U_MULTUSPARENTINTERFACE",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-edge-e1
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cuup-edge-e1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "CUUP_E1_MULTUSPARENTINTERFACE",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
