apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-edge-n3
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cuup-edge-n3",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "eth4",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "10.2.3.0/24", "gw": "10.0.6.1" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-edge-f1u
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cuup-edge-f1u",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "eth1",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-edge-e1
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cuup-edge-e1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "eth2",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
