apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-n2
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-n2",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "CUCP_N2_MASTER_INT",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "AMF_N2_NW_ADDRESS", "gw": "CUCP_N2_GW" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-f1c
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-f1c",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "CUCP_F1C_MASTER_INT",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-e1
  namespace: example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-e1",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "CUCP_E1_MASTER_INT",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }