apiVersion: v1
kind: ConfigMap
metadata:
  name: network-config-params
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CUCP_N2_IP: 10.0.3.16/24 # kpt-set: ${cucp-n2-ip-address}
  CUCP_N2_GW: 10.0.3.1 # kpt-set: ${cucp-n2-gateway}
  CUCP_N2_MASTER_INT: eth1
  CUCP_F1C_IP: 10.0.4.16/24 # kpt-set: ${cucp-f1c-ip-address}
  CUCP_F1C_GW: 10.0.4.1 # kpt-set: ${cucp-f1c-gateway}
  CUCP_F1C_MASTER_INT: eth2
  CUCP_E1_IP: 10.0.5.16/24 # kpt-set: ${cucp-e1-ip-address}
  CUCP_E1_GW: 10.0.5.1 # kpt-set: ${cucp-e1-gateway}
  CUCP_E1_MASTER_INT: eth3 
  AMF_N2_NW_ADDRESS: 10.0.6.0/24