apiVersion: v1
kind: ConfigMap
metadata:
  name: network-config-params
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  CUCP_N2_IP: N2_IP # kpt-set: ${cucp-n2-ip-address}
  CUCP_N2_GW: N2_GW # kpt-set: ${cucp-n2-gateway}
  CUCP_N2_MASTER_INT: N2_INTERFACE # kpt-set: ${cucp-n2-multus-interface}
  CUCP_F1C_IP: F1C_IP # kpt-set: ${cucp-f1c-ip-address}
  CUCP_F1C_GW: F1C_GW # kpt-set: ${cucp-f1c-gateway}
  CUCP_F1C_MASTER_INT: N2_INTERFACE # kpt-set: ${cucp-f1c-multus-interface}
  CUCP_E1_IP: E1_IP # kpt-set: ${cucp-e1-ip-address}
  CUCP_E1_GW: E1_GW # kpt-set: ${cucp-e1-gateway}
  CUCP_E1_MASTER_INT: N2_INTERFACE # kpt-set: ${cucp-e1-multus-interface}
  AMF_N2_NW_ADDRESS: AMF_N2_NW_ADDR # kpt-set: ${amf-n2-network-address}