apiVersion: v1
kind: ConfigMap
metadata:
  name: network-config
  namespace: porch-system
data:
  network-config.yaml: |
    cniPlugin: ipvlan
    amf:
      interfaces: 
        n2:
          ip: "10.1.3.16/24"
          networkAddress: "10.1.3.0/24"
          gw: "10.1.3.1"
          multusParentInterface: "eth1"
    smf:
      interfaces: 
        n4:
          ip: "10.1.4.16/24"
          networkAddress: "10.1.4.0/24"
          gw: "10.1.4.1"
          multusParentInterface: "eth2" 
    upf:
      interfaces: 
        n3:
          ip: "10.2.3.16/24"
          networkAddress: "10.2.3.0/24"
          gw: "10.2.3.1"
          multusParentInterface: "eth1"
        n4:
          ip: "10.2.4.16/24"
          networkAddress: "10.2.4.0/24"
          gw: "10.2.4.1"
          multusParentInterface: "eth2"
        n6:
          ip: "10.2.5.16/24"
          networkAddress: "10.2.5.0/24"
          gw: "10.2.5.1"
          multusParentInterface: "eth3"
    cucp:
      interfaces: 
        n2:
          ip: "10.0.5.16/24"
          networkAddress: "10.0.5.0/24"
          gw: "10.0.5.1"
          multusParentInterface: "ens8"
        e1:
          ip: "10.0.4.16/24"
          networkAddress: "10.0.4.0/24"
          gw: "10.0.4.1"
          multusParentInterface: "ens7"
        f1c:
          ip: "10.0.3.16/24"
          networkAddress: "10.0.3.0/24"
          gw: "10.0.3.1"
          multusParentInterface: "ens6"
    cuup:
      interfaces: 
        n3:
          ip: "10.0.6.16/24"
          networkAddress: "10.0.6.0/24"
          gw: "10.0.6.1"
          multusParentInterface: "ens9"
        e1:
          ip: "10.0.4.17/24"
          networkAddress: "10.0.4.0/24"
          gw: "10.0.4.1"
          multusParentInterface: "ens7"
        f1u:
          ip: "10.0.3.17/24"
          networkAddress: "10.0.3.0/24"
          gw: "10.0.3.1"
          multusParentInterface: "ens6"
    du:
      interfaces:
        f1u:
          ip: "10.0.3.18/24"
          networkAddress: "10.0.3.0/24"
          gw: "10.0.3.1"
          multusParentInterface: "ens6"