apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: eks-infra-tf-repo
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/infinitydon/eks-infra-terraform/
  ref:
    branch: main