apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: udm-example
  namespace: udm-example
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
spec:
  provider: udm.openairinterface.org