apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n3
  namespace: upf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "upf-core-n3",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "eth1",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "10.0.6.0/24", "gw": "10.2.3.1" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n4
  namespace: upf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "upf-core-n4",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "eth2",
          "mode": "l2",
          "ipam": {
            "type": "static",
            "routes": [{ "dst": "10.1.4.0", "gw": "10.2.4.1" }]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n6
  namespace: upf-example
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "upf-core-n6",
      "plugins": [
        {
          "type": "ipvlan",
          "capabilities": {
            "ips": true
          },
          "master": "eth3",
          "mode": "l2",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
